// AUTO-GENERATED FILE, DO NOT EDIT
use crate::unit::{UnitTypeData, Trait};

pub static UNIT_TYPE_DATA: &[UnitTypeData] = &[
    UnitTypeData { name: "Archer", cost: 3, max_hp: 100, attack: 20, defense: 10, range: 2, traits: &[Trait::Dash, Trait::Fortify] },
    UnitTypeData { name: "BabyDragon", cost: 10, max_hp: 150, attack: 30, defense: 30, range: 1, traits: &[Trait::Dash, Trait::Escape, Trait::Grow, Trait::Scout, Trait::Static] },
    UnitTypeData { name: "BattleSled", cost: 5, max_hp: 150, attack: 30, defense: 20, range: 1, traits: &[Trait::Dash, Trait::Escape, Trait::Skate] },
    UnitTypeData { name: "Catapult", cost: 8, max_hp: 100, attack: 40, defense: 0, range: 3, traits: &[Trait::Stiff] },
    UnitTypeData { name: "Centipede", cost: 10, max_hp: 200, attack: 40, defense: 30, range: 1, traits: &[Trait::Creep, Trait::Dash, Trait::Eat, Trait::Static] },
    UnitTypeData { name: "Cloak", cost: 8, max_hp: 50, attack: 20, defense: 5, range: 1, traits: &[Trait::Creep, Trait::Dash, Trait::Hide, Trait::Infiltrate, Trait::Scout, Trait::Static, Trait::Stiff] },
    UnitTypeData { name: "Crab", cost: 10, max_hp: 400, attack: 40, defense: 40, range: 1, traits: &[Trait::Autoflood, Trait::Escape, Trait::Static] },
    UnitTypeData { name: "Dagger", cost: 2, max_hp: 100, attack: 20, defense: 20, range: 1, traits: &[Trait::Dash, Trait::Independent, Trait::Static, Trait::Surprise] },
    UnitTypeData { name: "DefaultWarrior", cost: 2, max_hp: 100, attack: 20, defense: 20, range: 1, traits: &[Trait::Dash, Trait::Fortify] },
    UnitTypeData { name: "Defender", cost: 3, max_hp: 150, attack: 10, defense: 30, range: 1, traits: &[Trait::Fortify] },
    UnitTypeData { name: "Doomux", cost: 10, max_hp: 200, attack: 40, defense: 20, range: 1, traits: &[Trait::Creep, Trait::Dash, Trait::Explode] },
    UnitTypeData { name: "Egg", cost: 10, max_hp: 100, attack: 0, defense: 20, range: 1, traits: &[Trait::Fortify, Trait::Grow, Trait::Static, Trait::Stiff] },
    UnitTypeData { name: "Exida", cost: 8, max_hp: 100, attack: 30, defense: 10, range: 3, traits: &[Trait::Poison] },
    UnitTypeData { name: "FireDragon", cost: 10, max_hp: 200, attack: 40, defense: 30, range: 2, traits: &[Trait::Dash, Trait::Scout, Trait::Splash, Trait::Static] },
    UnitTypeData { name: "Gaami", cost: 10, max_hp: 300, attack: 40, defense: 30, range: 1, traits: &[Trait::AutoFreeze, Trait::FreezeArea, Trait::Static] },
    UnitTypeData { name: "Giant", cost: 10, max_hp: 400, attack: 50, defense: 40, range: 1, traits: &[Trait::Static] },
    UnitTypeData { name: "Hexapod", cost: 3, max_hp: 50, attack: 30, defense: 10, range: 1, traits: &[Trait::Creep, Trait::Dash, Trait::Escape, Trait::Sneak] },
    UnitTypeData { name: "IceArcher", cost: 3, max_hp: 100, attack: 0, defense: 10, range: 2, traits: &[Trait::Dash, Trait::Fortify, Trait::Freeze, Trait::Stiff] },
    UnitTypeData { name: "IceFortress", cost: 15, max_hp: 200, attack: 40, defense: 30, range: 2, traits: &[Trait::Scout, Trait::Skate] },
    UnitTypeData { name: "Jelly", cost: 8, max_hp: 200, attack: 20, defense: 20, range: 1, traits: &[Trait::Static, Trait::Stiff, Trait::Tentacles] },
    UnitTypeData { name: "Juggernaut", cost: 10, max_hp: 400, attack: 40, defense: 40, range: 1, traits: &[Trait::Carry, Trait::Static, Trait::Stiff, Trait::Stomp] },
    UnitTypeData { name: "Kiton", cost: 3, max_hp: 150, attack: 10, defense: 30, range: 1, traits: &[Trait::Poison] },
    UnitTypeData { name: "Knight", cost: 8, max_hp: 100, attack: 35, defense: 10, range: 1, traits: &[Trait::Dash, Trait::Persist] },
    UnitTypeData { name: "MindBender", cost: 5, max_hp: 100, attack: 0, defense: 10, range: 1, traits: &[Trait::Convert, Trait::Heal, Trait::Stiff] },
    UnitTypeData { name: "Mooni", cost: 5, max_hp: 100, attack: 0, defense: 10, range: 1, traits: &[Trait::AutoFreeze, Trait::Skate, Trait::Static, Trait::Stiff] },
    UnitTypeData { name: "Phychi", cost: 3, max_hp: 50, attack: 10, defense: 10, range: 2, traits: &[Trait::Dash, Trait::Poison, Trait::Surprise] },
    UnitTypeData { name: "Pirate", cost: 2, max_hp: 100, attack: 20, defense: 10, range: 1, traits: &[Trait::Dash, Trait::Independent, Trait::Static, Trait::Surprise] },
    UnitTypeData { name: "Polytaur", cost: 3, max_hp: 150, attack: 30, defense: 10, range: 1, traits: &[Trait::Dash, Trait::Fortify, Trait::Independent, Trait::Static] },
    UnitTypeData { name: "Puffer", cost: 8, max_hp: 100, attack: 40, defense: 0, range: 3, traits: &[Trait::Drench] },
    UnitTypeData { name: "Raychi", cost: 8, max_hp: 150, attack: 30, defense: 20, range: 1, traits: &[Trait::Creep, Trait::Dash, Trait::Explode, Trait::Navigate] },
    UnitTypeData { name: "Rider", cost: 3, max_hp: 100, attack: 20, defense: 10, range: 1, traits: &[Trait::Dash, Trait::Escape, Trait::Fortify] },
    UnitTypeData { name: "Segment", cost: 1, max_hp: 50, attack: 20, defense: 15, range: 1, traits: &[Trait::Explode, Trait::Static, Trait::Stiff] },
    UnitTypeData { name: "Shaman", cost: 5, max_hp: 100, attack: 10, defense: 10, range: 1, traits: &[Trait::Boost, Trait::Convert, Trait::Static] },
    UnitTypeData { name: "Shark", cost: 8, max_hp: 100, attack: 35, defense: 20, range: 1, traits: &[Trait::Dash, Trait::Surprise] },
    UnitTypeData { name: "Swordsman", cost: 5, max_hp: 150, attack: 30, defense: 30, range: 1, traits: &[Trait::Dash] },
    UnitTypeData { name: "Tridention", cost: 8, max_hp: 100, attack: 25, defense: 10, range: 2, traits: &[Trait::Dash, Trait::Persist] },
    UnitTypeData { name: "Warrior", cost: 2, max_hp: 100, attack: 20, defense: 20, range: 1, traits: &[Trait::Dash, Trait::Fortify] },
];
